### ISSUE TITLE
Please create release

### ISSUE THREAD

**Issue by repat** [tmaciej/monolog-pushbullet#2]
Hi,
could you make a release of this? That way my composer won't show this message:

> [InvalidArgumentException] Could not find package tmaciej/monolog-pushbullet at any
> version for your minimum-stability (stable). Check the package spelling
> or your minimum-stability

The version in the composer.json is 1.0.0-alpha, so all you would have to do
is go to https://github.com/tmaciej/monolog-pushbullet, click on "0 releases" and create
one for 1.0.0(-alpha)

(Also, on another note, I created a pull request with support for selecting a device which would be important for me, thanks :))

**Comment by tmaciej** [comment]
Made a release. Thanks for your contribution :)
